# docker-compose.yml
version: "3.9"
services:
  web:
    build: .
    restart: always
    command: sh -c "service cron start && gunicorn --bind 0.0.0.0:5000 --log-level debug --timeout 90 --workers 4 app:app"
    ports:
      - "80:5000"
    environment:
      DATABASE_URL: postgresql://postgres:example@35.226.170.82:5432/example
      CELERY_RESULT_BACKEND: redis://34.171.206.48:6379/0
      PUERTO_SMTP: 587
      CELERY_BROKER_URL: redis://34.171.206.48:6379/0
      CORREO_ELECTRONICO: "clouduniandesmiso@hotmail.com"
      SERVIDOR_SMTP: "smtp-mail.outlook.com"
      USUARIO_SMTP: "clouduniandesmiso@hotmail.com"
      PASSWORD_SMTP: "12uniandes12"
      JWT_ALGORITHM: "HS256"
      JWT_SECRET_KEY: "frase-secreta"

