# docker-compose.yml

version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  
  web:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    environment:
      DATABASE_URL: postgresql://example:example@db:5432/example
      BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      RESULT_BACKEND: db+postgresql://example:example@db:5432/example
      CORREO_ELECTRONICO: example@example.com
      SERVIDOR_SMTP: smtp.example.com
      PUERTO_SMTP: 587
      USUARIO_SMTP: example
      PASSWORD_SMTP: example
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"