  # docker-compose.yml

  version: "3.9"

  services:
    db:
      image: postgres:13
      restart: always
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_USER: example
        POSTGRES_DB: example
      volumes:
        - ./data:/var/lib/postgresql/data
      ports:
        - "5434:5432"
    
    web:
      build: .
      restart: always
      volumes:
        - .:/app
      ports:
        - "8000:5001"
      environment:
        DATABASE_URL: postgresql://example:example@db:5432/example
        CELERY_BROKER_URL: redis://redis:6379/0
        CELERY_RESULT_BACKEND: redis://redis:6379/0
        CORREO_ELECTRONICO: example@example.com
        SERVIDOR_SMTP: smtp.example.com
        PUERTO_SMTP: 587
        USUARIO_SMTP: example
        PASSWORD_SMTP: example
      depends_on:
        - db
        - redis

    worker:
      build: .
      command: celery --app=tasks.celery worker --loglevel=info
      volumes:
        - .:/usr/src/app
      environment:
        FLASK_DEBUG: 1
        APP_SETTINGS: app.server.config.DevelopmentConfig
        CELERY_BROKER_URL: redis://redis:6379/0
        CELERY_RESULT_BACKEND: redis://redis:6379/0
        DATABASE_URL: postgresql://example:example@db:5432/example
      depends_on:
        - web
        - redis

    redis:
      image: redis:6-alpine