# docker-compose.yml
version: "3.9"
services:
  web:
    build: .
    restart: always
    command: sh -c "service cron start && gunicorn --bind 0.0.0.0:5000 --log-level debug --timeout 90 --workers 4 app:app"
    ports:
      - "8000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:example@35.184.246.200:5432/example
      CELERY_RESULT_BACKEND: redis://104.154.208.42:6379/0
      PUERTO_SMTP: 587
      CELERY_BROKER_URL: redis://104.154.208.42:6379/0
      JWT_ALGORITHM: "HS256"
      JWT_SECRET_KEY: "frase-secreta"
