# docker-compose.yml
version: "3.9"
services:
    worker:
      build: .
      command: celery --app=tasks.celery worker --loglevel=info
      environment:
        DATABASE_URL: postgresql://example:example@33.33.33.33:5432/example
        CELERY_RESULT_BACKEND: redis://10.10.10.10:6379/0
        PUERTO_SMTP: 587
        CELERY_BROKER_URL: redis://10.10.10.10:6379/0
        CORREO_ELECTRONICO: 'clouduniandesmiso@hotmail.com'
        SERVIDOR_SMTP: 'smtp-mail.outlook.com'
        USUARIO_SMTP: 'clouduniandesmiso@hotmail.com'
        PASSWORD_SMTP: '12uniandes12'
        JWT_ALGORITHM: 'HS256'
        JWT_SECRET_KEY: 'frase-secreta'

