  # docker-compose.yml

  version: "3.9"

  services:
    db:
      image: postgres:13
      restart: always
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_USER: example
        POSTGRES_DB: example
      volumes:
        - ./data:/var/lib/postgresql/data
      ports:
        - "5434:5432"
    
    web:
      build: .
      restart: always
      volumes:
        - .:/app
        - ./uploads:/app/uploads
        - ${PWD}/uploads:/app/uploads
        - ${PWD}/uploads:/usr/src/app/uploads
        - ${PWD}/conversions:/app/conversions
        - ${PWD}/conversions:/usr/src/app/conversions
      ports:
        - "8000:5001"
      environment:
        DATABASE_URL: postgresql://example:example@db:5432/example
        CELERY_RESULT_BACKEND: redis://redis:6379/0
        PUERTO_SMTP: 587
        CELERY_BROKER_URL: redis://redis:6379/0
        CORREO_ELECTRONICO: 'clouduniandesmiso@hotmail.com'
        SERVIDOR_SMTP: 'smtp-mail.outlook.com'
        USUARIO_SMTP: 'clouduniandesmiso@hotmail.com'
        PASSWORD_SMTP: '12uniandes12'
        JWT_ALGORITHM: 'HS256'
        JWT_SECRET_KEY: 'frase-secreta'


      depends_on:
        - db
        - redis

    worker:
      build: .
      command: celery --app=tasks.celery worker --loglevel=info
      volumes:
        - .:/usr/src/app
        - .:/app
        - ./uploads:/usr/src/app/uploads
        - ${PWD}/uploads:/app/uploads
        - ${PWD}/uploads:/usr/src/app/uploads
        - ${PWD}/conversions:/app/conversions
        - ${PWD}/conversions:/usr/src/app/conversions
      environment:
        DATABASE_URL: postgresql://example:example@db:5432/example
        CELERY_RESULT_BACKEND: redis://redis:6379/0
        PUERTO_SMTP: 587
        CELERY_BROKER_URL: redis://redis:6379/0
        CORREO_ELECTRONICO: 'clouduniandesmiso@hotmail.com'
        SERVIDOR_SMTP: 'smtp-mail.outlook.com'
        USUARIO_SMTP: 'clouduniandesmiso@hotmail.com'
        PASSWORD_SMTP: '12uniandes12'
        JWT_ALGORITHM: 'HS256'
        JWT_SECRET_KEY: 'frase-secreta'
      depends_on:
        - web
        - redis

    redis:
      image: redis:6-alpine